version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      maven:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      angular:
        patterns: ['@angular/*', '@angular-devkit/*', 'typescript', 'zone.js']
      npm:
        patterns: ['*']
        exclude-patterns: ['@angular/*', '@angular-devkit/*', 'typescript', 'zone.js']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
